### ISSUE TITLE
Домашнее задание по тестированию

### ISSUE THREAD

**Issue by tiny-kottan** [chrom/cottans-js-2016#7]
https://github.com/timoxley/functional-javascript-workshop - complete 'Function Spies' exercise.
Investigate following questions:
  1) What are stubs, mocks? What is the difference?
  2) What is the difference between TDD and BDD?
Read about several test frameworks / setups, pick one (qunit, jasmine, mocha, ava, tape). 
Do Kata #1 using it.

**Comment by chrom** [comment]
https://github.com/chrom/cottans-js-2016/commit/ff150d7b4d450b0a111e9bb8c31c15aecc4eb4fe
